version: '3.9'

services:
  odoo:
    image: odoo:17
    container_name: rkt-odoo
    restart: ${RESTART_POLICY}
    # command: ["-i", "base", "-d", "odoo"]
    volumes:
      - ${ODOO_CONFIG_PATH}:/etc/odoo/odoo.conf
      - ${ODOO_EXTRA_ADDONS_PATH}:/mnt/extra-addons
    ports:
      - "8069:8069"
    environment:
      # - POSTGRES_DB=${POSTGRES_ODOO_DB}
      # - POSTGRES_USER=${POSTGRES_ODOO_USER}
      # - POSTGRES_PASSWORD=${POSTGRES_ODOO_PASSWORD}
      - DB_PORT_5432_TCP_ADDR